2025-03-20 10:21:00,642 - util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.000 seconds
2025-03-20 10:21:00,642 - url_helper.py[DEBUG]: [0/1] open 'http://[fe80::a9fe:a9fe]/openstack' with {'url': 'http://[fe80::a9fe:a9fe]/openstack', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:00,794 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/openstack' with {'url': 'http://169.254.169.254/openstack', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:01,321 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack (200, 105b) after 1 attempts
2025-03-20 10:21:01,322 - DataSourceOpenStack.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
2025-03-20 10:21:01,322 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack' with {'url': 'http://169.254.169.254/openstack', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:01,724 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack (200, 105b) after 1 attempts
2025-03-20 10:21:01,725 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack/2018-08-27/meta_data.json' with {'url': 'http://169.254.169.254/openstack/2018-08-27/meta_data.json', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:02,128 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack/2018-08-27/meta_data.json (200, 1894b) after 1 attempts
2025-03-20 10:21:02,129 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack/2018-08-27/user_data' with {'url': 'http://169.254.169.254/openstack/2018-08-27/user_data', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:03,249 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack/2018-08-27/user_data (200, 4b) after 1 attempts
2025-03-20 10:21:03,249 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack/2018-08-27/vendor_data.json' with {'url': 'http://169.254.169.254/openstack/2018-08-27/vendor_data.json', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:03,637 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack/2018-08-27/vendor_data.json (200, 2b) after 1 attempts
2025-03-20 10:21:03,637 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack/2018-08-27/vendor_data2.json' with {'url': 'http://169.254.169.254/openstack/2018-08-27/vendor_data2.json', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:04,029 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack/2018-08-27/vendor_data2.json (200, 14b) after 1 attempts
2025-03-20 10:21:04,029 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/openstack/2018-08-27/network_data.json' with {'url': 'http://169.254.169.254/openstack/2018-08-27/network_data.json', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:04,422 - url_helper.py[DEBUG]: Read from http://169.254.169.254/openstack/2018-08-27/network_data.json (200, 395b) after 1 attempts
2025-03-20 10:21:04,422 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/' with {'url': 'http://169.254.169.254/latest/meta-data/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:04,815 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ (200, 223b) after 1 attempts
2025-03-20 10:21:04,815 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:05,225 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-03-20 10:21:05,225 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:05,629 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ami (200, 3b) after 1 attempts
2025-03-20 10:21:05,629 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/root', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:06,022 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/root (200, 8b) after 1 attempts
2025-03-20 10:21:06,022 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/' with {'url': 'http://169.254.169.254/latest/meta-data/placement/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:07,200 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/ (200, 17b) after 1 attempts
2025-03-20 10:21:07,200 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:07,585 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone (200, 4b) after 1 attempts
2025-03-20 10:21:07,585 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-keys/' with {'url': 'http://169.254.169.254/latest/meta-data/public-keys/', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:07,980 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-keys/ (200, 13b) after 1 attempts
2025-03-20 10:21:07,980 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:08,390 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key (200, 404b) after 1 attempts
2025-03-20 10:21:08,390 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-id' with {'url': 'http://169.254.169.254/latest/meta-data/ami-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:08,795 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-id (200, 12b) after 1 attempts
2025-03-20 10:21:08,795 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/latest/meta-data/ami-launch-index', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:09,192 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-03-20 10:21:09,192 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/latest/meta-data/ami-manifest-path', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:09,587 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-manifest-path (200, 5b) after 1 attempts
2025-03-20 10:21:09,587 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/hostname' with {'url': 'http://169.254.169.254/latest/meta-data/hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:09,983 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/hostname (200, 47b) after 1 attempts
2025-03-20 10:21:09,984 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-action' with {'url': 'http://169.254.169.254/latest/meta-data/instance-action', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:10,375 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-action (200, 4b) after 1 attempts
2025-03-20 10:21:10,375 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:11,492 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 10b) after 1 attempts
2025-03-20 10:21:11,493 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-type' with {'url': 'http://169.254.169.254/latest/meta-data/instance-type', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:11,880 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-type (200, 11b) after 1 attempts
2025-03-20 10:21:11,880 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/local-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:12,272 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-hostname (200, 47b) after 1 attempts
2025-03-20 10:21:12,272 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/local-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:12,661 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-ipv4 (200, 11b) after 1 attempts
2025-03-20 10:21:12,661 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/public-hostname', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:13,061 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-hostname (200, 47b) after 1 attempts
2025-03-20 10:21:13,061 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/public-ipv4', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:13,465 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-ipv4 (200, 0b) after 1 attempts
2025-03-20 10:21:13,465 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/reservation-id' with {'url': 'http://169.254.169.254/latest/meta-data/reservation-id', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:13,861 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/reservation-id (200, 10b) after 1 attempts
2025-03-20 10:21:13,861 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/security-groups', 'stream': False, 'allow_redirects': True, 'method': 'GET', 'timeout': 10.0, 'headers': {'User-Agent': 'Cloud-Init/23.4-7.el9_4'}} configuration
2025-03-20 10:21:14,255 - url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/security-groups (200, 7b) after 1 attempts
2025-03-20 10:21:14,425 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: ['sysconfig', 'eni', 'netplan', 'network-manager', 'networkd']
2025-03-20 10:21:14,428 - util.py[DEBUG]: Writing to /etc/sysconfig/network-scripts/ifcfg-eth0 - wb: [644] 167 bytes
2025-03-20 10:21:14,429 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)
2025-03-20 10:21:14,430 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)
2025-03-20 10:21:14,434 - util.py[DEBUG]: Reading from /etc/sysconfig/network (quiet=True)
2025-03-20 10:21:14,434 - util.py[DEBUG]: Read 30 bytes from /etc/sysconfig/network
2025-03-20 10:21:14,434 - util.py[DEBUG]: Writing to /etc/sysconfig/network - wb: [644] 85 bytes
2025-03-20 10:21:14,435 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)
2025-03-20 10:21:14,436 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)
2025-03-20 10:21:15,653 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'None'...'