{"name": "insights.specs.Specs.udev_fc_wwpn_id_rules", "exec_time": 7.009506225585938e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/plugins.py\", line 101, in invoke\n    return self.component(broker)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 709, in __call__\n    return self.kind(\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 213, in __init__\n    self.validate()\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 218, in validate\n    raise ContentException(\"%s does not exist.\" % self.path)\ninsights.core.exceptions.ContentException: /usr/lib/udev/rules.d/59-fc-wwpn-id.rules does not exist.\n"], "results": null, "ser_time": 5.4836273193359375e-06}